version: '3.8'
services:
  chatgpt-proxy-node:
    image: hanglegehang/chatgpt-proxy-node:latest
    restart: always
    container_name: chatgpt-proxy-node
    ports:
      - 8100:8100
    environment:
      TZ: Asia/Shanghai # 指定时区

    volumes:
      - ./config.yaml:/app/config.yaml
    labels:
      - "com.centurylinklabs.watchtower.scope=hanglegehang-chatgpt-proxy-node"